In [2]:
import tensorflow as tf

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
df.shape

(10000, 14)

In [6]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
import seaborn as sns

In [8]:
X = df.iloc[:, 3:13]
y = df.iloc[:, 13]

In [9]:
geography = pd.get_dummies(X['Geography'], drop_first=True)
gender = pd.get_dummies(X['Gender'], drop_first=True)

In [10]:
geography.head()

Germany  Spain
0        0      0
1        0      1
2        0      0
3        0      0
4        0      1

In [11]:
X = pd.concat([X, geography,gender], axis=1)

In [12]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Germany  Spain  Male  
0          1               1        101348.88        0      0     0  
1          0               1        112542.58        0      1     0  
2          1               0        113931.57        0      0     0  
3          0               0         93826.63        0      0     0  
4          1               1         79084.10        0      1     0

In [13]:
X = X.drop(['Geography','Gender'], axis=1)

In [14]:
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Germany  Spain  Male  
0               1        101348.88        0      0     0  
1               1        112542.58        0      1     0  
2               0        113931.57        0      0     0  
3               0         93826.63        0      0     0  
4               1         79084.10        0      1     0

In [15]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
sc = StandardScaler()

In [19]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [20]:
import keras

In [21]:
from keras.models import Sequential

In [22]:
from keras.layers import Dense

In [23]:
from keras.layers import Dropout

In [24]:
from keras.layers import LeakyReLU,PReLU,ELU

In [25]:
X_train.shape

(8000, 11)

In [26]:
#Initializing ANN
Classifier =Sequential()

In [27]:
#Adding input layer & first hidden layer
Classifier.add(Dense(units = 6, kernel_initializer = 'he_uniform', activation='relu', input_dim = 11))

In [28]:
#Adding second hidden layer
Classifier.add(Dense(units=6, kernel_initializer = 'he_uniform', activation='relu'))

In [29]:
#Adding output layer
Classifier.add(Dense(units=1, kernel_initializer = 'glorot_uniform', activation='sigmoid'))

In [30]:
Classifier.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 6)                 72        
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 7         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


In [31]:
#Compiling ANN
Classifier.compile(optimizer='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [32]:
model_history = Classifier.fit(X_train, y_train,validation_split=0.33, batch_size=10, epochs= 100)

Epoch 1/100
536/536 [==============================] - 63s 9ms/step - loss: 0.8544 - accuracy: 0.5217 - val_loss: 0.5279 - val_accuracy: 0.7955
Epoch 2/100
536/536 [==============================] - 2s 4ms/step - loss: 0.5181 - accuracy: 0.7914 - val_loss: 0.4837 - val_accuracy: 0.8016
Epoch 3/100
536/536 [==============================] - 2s 4ms/step - loss: 0.4611 - accuracy: 0.8070 - val_loss: 0.4573 - val_accuracy: 0.8027
Epoch 4/100
536/536 [==============================] - 3s 5ms/step - loss: 0.4527 - accuracy: 0.8035 - val_loss: 0.4444 - val_accuracy: 0.8050
Epoch 5/100
536/536 [==============================] - 2s 4ms/step - loss: 0.4259 - accuracy: 0.8203 - val_loss: 0.4396 - val_accuracy: 0.8122
Epoch 6/100
536/536 [==============================] - 2s 4ms/step - loss: 0.4173 - accuracy: 0.8172 - val_loss: 0.4355 - val_accuracy: 0.8122
Epoch 7/100
536/536 [==============================] - 2s 4ms/step - loss: 0.4081 - accuracy: 0.8245 - val_loss: 0.4324 - val_accuracy: 0.809

Epoch 58/100
536/536 [==============================] - 3s 5ms/step - loss: 0.3214 - accuracy: 0.8544 - val_loss: 0.3612 - val_accuracy: 0.8504
Epoch 59/100
536/536 [==============================] - 3s 5ms/step - loss: 0.3185 - accuracy: 0.8608 - val_loss: 0.3599 - val_accuracy: 0.8538
Epoch 60/100
536/536 [==============================] - 2s 5ms/step - loss: 0.3338 - accuracy: 0.8565 - val_loss: 0.3595 - val_accuracy: 0.8519
Epoch 61/100
536/536 [==============================] - 3s 5ms/step - loss: 0.3320 - accuracy: 0.8571 - val_loss: 0.3599 - val_accuracy: 0.8531
Epoch 62/100
536/536 [==============================] - 2s 5ms/step - loss: 0.3257 - accuracy: 0.8639 - val_loss: 0.3604 - val_accuracy: 0.8512
Epoch 63/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3412 - accuracy: 0.8519 - val_loss: 0.3596 - val_accuracy: 0.8550
Epoch 64/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3279 - accuracy: 0.8630 - val_loss: 0.3641 - val_accuracy:

In [33]:
y_pred = Classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [34]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [35]:
from sklearn.metrics import confusion_matrix

In [36]:
cm = confusion_matrix(y_test, y_pred)

In [37]:
cm

array([[1504,   91],
       [ 188,  217]], dtype=int64)

In [38]:
from sklearn.metrics import accuracy_score

In [39]:
score = accuracy_score(y_pred, y_test)

In [40]:
score

0.8605

In [41]:
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Germany  Spain  Male  
0               1        101348.88        0      0     0  
1               1        112542.58        0      1     0  
2               0        113931.57        0      0     0  
3               0         93826.63        0      0     0  
4               1         79084.10        0      1     0

In [42]:
Classifier.predict([[902,66,10,105000,1,1,1,90000,1,0,1]])

array([[1.]], dtype=float32)